.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH GIT-REMOTE-OBJECT-STORE-UNPROTECT 1  git-remote-object-store "git-remote-object-store Manual"
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH NAME
git\-remote\-object\-store\-unprotect \- Remove the `PROTECTED#` sentinel from a branch
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH SYNOPSIS
\fBgit\-remote\-object\-store\-unprotect\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIREMOTE\fR> <\fIBRANCH\fR> 
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH DESCRIPTION
Remove the `PROTECTED#` sentinel from a branch
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIREMOTE\fR>
A remote URL (`s3+https://…`, `az+https://…`) or the name of a git remote configured in the current repository
.TP
<\fIBRANCH\fR>
Branch name, without the `refs/heads/` prefix
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH SUBCOMMANDS
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH EXTRA
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH AUTHORS

